---
- name: Install dependencies
      become: true
      become_user: root
      ansible.builtin.yum:
        name:
          - epel-release
          - git
- name: Create nginx path
  become: true
  ansible.builtin.file:
    mode: "755"
    owner: "{{ user_id }}"
    group: "{{ user_group_id }}"
    path: "/var/www"
    state: "directory"
- name: Create nginx log path
  become: true
  ansible.builtin.file:
    mode: "755"
    owner: "{{ user_id }}"
    group: "{{ user_group_id }}"
    path: "/var/log/nginx"
    state: "directory"
- name: Clone lighthouse repository
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    dest: "{{ lighthouse_path }}"
    version: "{{ lighthouse_vcs_version }}"
- name: Selinux add permissions
  become: true
  ansible.builtin.command:
    cmd: chcon -Rt httpd_sys_content_t /var/www
  changed_when: false
- name: Install nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
- name: Nginx configure
  become: true
  ansible.builtin.template:
    src: "./templates/nginx/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: "755"
- name: Nginx lighthouse configure
  become: true
  ansible.builtin.template:
    src: "./templates/nginx/nginx.lighthouse.conf.j2"
    dest: "/etc/nginx/conf.d/lighthouse.conf"
    mode: "755"
- name: Start nginx service
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
- name: Check service
  ansible.builtin.uri:
    url: http://localhost

